### PR TITLE
Support getting io.popen results on file:close() on PUC-Rio Lua 5.1

### PR DESCRIPTION
**Pull request by hishamhm**

### CODE REVIEW

**Comment by daurnimator** [comment]
Is there any thing in particular I should look out for when reviewing this PR?

**Comment by hishamhm** [comment]
@daurnimator I followed the patterns used to load the string packing functions, and also tried to make it conditional to PUC-Rio Lua 5.1 only via ifdefs. The idea is that those changes should have no effect on other Lua versions.

**Comment by hishamhm** [comment]
I've been pinged about this behavior in https://github.com/teal-language/tl/pull/687 — I'm inclined to merge this and push a release if nobody else has objections. @siffiejoe?

**Comment by daurnimator** [comment]
no major objections from me

**Pull request merged**
